Include the command output and exit status in the e-mail body

diff --git a/emailafter b/emailafter
--- a/emailafter
+++ b/emailafter
@@ -4,7 +4,19 @@ NAME="emailafter"
 CODENAME="emailafter"
 COPYRIGHT="Copyright (C) 2018 Nathan Shearer"
 LICENSE="GNU General Public License 2.0"
-VERSION="1.0.1.0"
+VERSION="1.1.0.0"
+
+# \brief Ensures dependencies are present
+# \param $@ The dependencies to check for
+function emailafter_check_dependencies
+{
+	for TOOL in "$@"; do
+		if ! type "$TOOL" >/dev/null 2>/dev/null; then
+			echo "$CODENAME: \"$TOOL\" is required for this application to work correctly." >&2
+			exit
+		fi
+	done
+}
 
 # \brief Displays the help and exits the program
 function emailafter_help
@@ -34,6 +46,10 @@ function emailafter_help
 	exit
 }
 
+#------------------------------------------------------------------------------
+# command line arguments
+#
+
 if [ $# -eq 0 -o "$1" = "-h" -o "$1" = "--help" ]; then
 	emailafter_help
 fi
@@ -50,8 +66,44 @@ fi
 EMAIL="$1"
 shift
 
-"$@"
+#------------------------------------------------------------------------------
+# prepare environment
+#
+
+emailafter_check_dependencies hostname mail stdbuf
+TMP="/tmp/$CODENAME.$$"
+mkdir -p "$TMP"
+
+#------------------------------------------------------------------------------
+# begin execution
+#
+
+mkfifo "$TMP"/stdout
+mkfifo "$TMP"/stderr
+touch "$TMP"/output.log
+stdbuf -oL -eL tee -a "$TMP"/output.log <"$TMP"/stdout &
+stdbuf -oL -eL tee -a "$TMP"/output.log <"$TMP"/stderr >&2 &
+
+stdbuf -oL -eL "$@" >"$TMP"/stdout 2>"$TMP"/stderr
 STATUS="$?"
 
-echo "The following command has completed: \"$@\"" | mail -s "$(hostname --fqdn): command complete" "$EMAIL"
+HOSTNAME=$(hostname --fqdn)
+PWD=$(pwd)
+USER_ID=$(id -u)
+if [ $(id -u) = 0 ]; then
+	echo -n "$HOSTNAME $PWD # " >"$TMP"/email.txt
+else
+	USER_NAME=$(id -un)
+	echo -n "$USER_NAME@$HOSTNAME $PWD \$ " >"$TMP"/email.txt
+fi
+
+echo "$@" >>"$TMP"/email.txt
+echo >>"$TMP"/email.txt
+cat "$TMP"/output.log >>"$TMP"/email.txt
+echo >>"$TMP"/email.txt
+echo "Exit Status: $STATUS" >>"$TMP"/email.txt
+
+cat "$TMP"/email.txt | mail -s "$(hostname --fqdn): command complete" "$EMAIL"
+
+rm -rf "$TMP"
 exit "$STATUS"
